project_id = "beyond-peps"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://beyondpeps.vercel.app"
additional_redirect_urls = [
  "https://beyondpeps.vercel.app/account.html",
  "https://beyondpeps.com",
  "https://beyondpeps.com/account.html",
  "https://www.beyondpeps.com",
  "https://www.beyondpeps.com/account.html"
]
