create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text not null,
  anonymous_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  page_path text not null default '',
  product_id text,
  order_id uuid references public.orders(id) on delete set null,
  value_cents integer,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists analytics_events_occurred_at_idx on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_name_date_idx on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_events_session_idx on public.analytics_events (session_id);

alter table public.analytics_events enable row level security;

drop policy if exists "Admins view analytics events" on public.analytics_events;
create policy "Admins view analytics events"
  on public.analytics_events
  for select
  to authenticated
  using (public.beyond_peps_is_admin());

create or replace function public.track_analytics_event(
  p_event_name text,
  p_session_id text,
  p_anonymous_id text,
  p_page_path text default '',
  p_product_id text default null,
  p_order_id uuid default null,
  p_value_cents integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_name not in (
    'page_view',
    'view_item',
    'add_to_cart',
    'remove_from_cart',
    'view_cart',
    'begin_checkout',
    'add_shipping_info',
    'purchase',
    'newsletter_signup',
    'login',
    'sign_up'
  ) then
    raise exception 'Unsupported analytics event.';
  end if;

  insert into public.analytics_events (
    event_name,
    session_id,
    anonymous_id,
    user_id,
    page_path,
    product_id,
    order_id,
    value_cents,
    metadata
  )
  values (
    left(coalesce(p_event_name, ''), 64),
    left(coalesce(p_session_id, ''), 128),
    left(coalesce(p_anonymous_id, ''), 128),
    auth.uid(),
    left(coalesce(p_page_path, ''), 500),
    left(p_product_id, 200),
    p_order_id,
    p_value_cents,
    coalesce(p_metadata, '{}'::jsonb)
  );
end
$$;

grant execute on function public.track_analytics_event(text, text, text, text, text, uuid, integer, jsonb) to anon, authenticated;
